/*
A monoalphabetic substitution cipher:
Each letter of the plaintext is consistently replaced by a different letter or symbol. 
The key to this cipher is the fixed, one-to-one mapping between the plaintext and ciphertext alphabets. 

Key characteristics:
- Fixed substitution: The same letter in the plaintext will always be encrypted to the same ciphertext letter 
throughout the entire message.
- Key: The key is the secret mapping, which can be generated by various methods, such as using a KEYWORD to 
create a shuffled cipher alphabet.

Example:
    Plaintext: ATTACK
    Key: A mapping where A becomes K, T becomes A, C becomes M, and K becomes C.
    Ciphertext: KAAKMC 

Mathematical Expression:
- For Encryption: C=( P + K ) mod 26 where 'P' is the character in plain text, 'K' is the key, and 'C' is the Cipher.
- For Decryption: P=( C - K ) mod 26.

Example: 
Input: P= GEEKS , Key= 4 . Output : C=KIIOW
*/
#include <iostream>
#include <string>

int main () {
    // generate secret mapping with KEYWORD
    std::string plaintext = "SOMETEXT";
    std::string key = "ZEBRA";
    char alphabet_lower = 'A';
    char alphabet_upper = 'Z';
    std::string secret_mapping = key;

    // Start with key -> add rest of values in increasing order
    // 90 69 66 82 65 
}

